# Generated by Django 3.1.8 on 2021-05-24 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_log_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='owner',
        ),
    ]
