# Generated by Django 3.1.8 on 2021-05-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_log_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='start_data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
