# Generated by Django 3.1.8 on 2021-05-25 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_auto_20210524_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='owner',
        ),
    ]
